Update adventure
FrankHeijden/ServerUtils pull request #57
Opened 2022-08-21 13:52 UTC by d0by1

Hello, so I found that some dependencies were out of date. I updated hopefully most of them. 

Anyhow, there has also been an issue with the kyori adventure library which has been sending some wrong packets or whatnot in the current version and basically didn't work properly with ViaVersion, updating it to 4.1.2 resolves the problem and everything works fine. So I even managed to fix that. 

There is more info on this adventure bug here: https://github.com/ViaVersion/ViaVersion/issues/3070

2022-08-21 14:30 UTC, FrankHeijden commented
Hmm, I reckon there were issues with newer versions of adventure on the old™️, could you test this on older versions?

2022-08-21 15:28 UTC, d0by1 commented
Older versions of what you mean exactly? I will test it, that's no problem.

2022-08-21 19:28 UTC, FrankHeijden commented
Older Minecraft versions ^^ since ServerUtils supports 1.8.8 - 1.19.2

2022-08-22 11:25 UTC, d0by1 commented
So, I tested it on 1.8.8, 1.12.2 and 1.19. Everything works fine and I haven't found any problems. You are using an outdated version of MiniMessage and updating it would require a lot of work as there have been some critical changes to the api. I just left the version you were using which works fine. The only problem, with ViaVersion, was adventure-platform-bukkit, which I updated fixing the problem.

2022-08-22 12:40 UTC, FrankHeijden requested changes
Looks good, just one final thingy

2022-08-22 12:40 UTC, FrankHeijden commented on Bukkit/build.gradle.kts
> +        exclude("net.kyori", "adventure-text-minimessage")
These exclusions will also have to be added for the Bungee module

2022-08-22 12:57 UTC, FrankHeijden approved these changes

2022-08-22 12:58 UTC, merged

2022-10-11 07:36 UTC, FrankHeijden commented
Older Minecraft versions ^^ since ServerUtils supports 1.8.8 - 1.19.2On 21 Aug 2022, at 17:28, d0by ***@***.***> wrote:﻿
Older versions of what you mean exactly? I will test it, that's no problem.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2022-10-11 08:37 UTC, FrankHeijden commented
> Older Minecraft versions ^^ since ServerUtils supports 1.8.8 - 1.19.2On 21 Aug 2022, at 17:28, d0by ***@***.***> wrote:﻿ Older versions of what you mean exactly? I will test it, that's no problem. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

hm yes i replied via mail like 2mo ago, and when it wasnt working i just commented.. nice of you github to show it now (: